### ISSUE TITLE
same album name different artists are mixed in album view mode 

### ISSUE THREAD

**Issue by nicotux** [r10s/silverjuke#69]
Hi,
a problem with silverjuke database sorting: when several Artists have same name for an Album, their songs simply mix under the name of the album... Imagine best of or medleys
(Silverjuke master branch with linux)

**Comment by r10s** [comment]
You can tweak this at "Settings / Jukebox / Combine tracks to albums" - if you have a strict music archive using one directory per album, you can define this here to fix the issue. Otherwise playing around with different values may get better results, however, you probably won't get 100% this way (unfortunately, there is no easy and save way to combine independent tracks to albums).

![combine](https://cloud.githubusercontent.com/assets/9800740/13619410/1ad2439c-e589-11e5-9c7a-94871e4bb1fb.png)
